name       : utsushi
version    : 3.55.0
release    : 9
source     :
    - http://support.epson.net/linux/src/scanner/imagescanv3/debian/imagescan_3.55.0.orig.tar.gz : 9440b103b8218863ab08e891d2a9dc9ef52db51485e11017d52fb2036e279477
license    : GPL-3.0-or-later
component  : office
summary    : Utsushi - Next Generation Image Acquisition
description: |
    Utsushi for Epson scanning, replaces iscan/imagescan
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(GraphicsMagick++)
    - pkgconfig(ImageMagick)
    - pkgconfig(libtiff-4)
    - pkgconfig(libudev)
    - pkgconfig(libusb-1.0)
    - pkgconfig(sane-backends)
    - libboost-devel
    - libjpeg-turbo-devel
setup      : |
    %configure --with-udev-confdir=/usr/lib64/udev \
               --enable-sane-config \
               --enable-udev-config
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/utsushi.desktop $installdir/usr/share/applications/utsushi.desktop
