name       : utsushi
version    : 3.32.0
release    : 4
source     :
    - http://support.epson.net/linux/src/scanner/imagescanv3/debian/imagescan_3.32.0.orig.tar.gz : debaf772a5ace565ca7c65d07ea73f7553db15c7bbb4f45cb50365266ab144ac
license    : GPL-3.0
component  : office
summary    : Utsushi - Next Generation Image Acquisition
description: |
    Utsushi for Epson scanning, replaces iscan/imagescan
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(GraphicsMagick++)
    - pkgconfig(ImageMagick)
    - pkgconfig(libtiff-4)
    - pkgconfig(libudev)
    - pkgconfig(libusb-1.0)
    - pkgconfig(sane-backends)
    - libboost-devel
    - libjpeg-turbo-devel
setup      : |
    %configure --with-udev-confdir=/usr/lib64/udev \
               --enable-sane-config \
               --enable-udev-config
build      : |
    %make
install    : |
    %make_install
    install -Dm 00644 $pkgfiles/utsushi.desktop $installdir/usr/share/applications/utsushi.desktop
