name       : utsushi
version    : 3.29.0
release    : 1
source     :
    - http://support.epson.net/linux/src/scanner/imagescanv3/debian/imagescan_3.29.0.orig.tar.gz : 0e020a2865b38b344b6a68928f16f32829b2c641179bc02492db94c79b9a9c22
license    : GPL-3.0
component  : office
summary    : Utsushi - Next Generation Image Acquisition
description: |
    Utsushi for Epson scanning, replaces iscan/imagescan
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(GraphicsMagick++)
    - pkgconfig(ImageMagick)
    - pkgconfig(libtiff-4)
    - pkgconfig(libudev)
    - pkgconfig(libusb-1.0)
    - pkgconfig(sane-backends)
    - libboost-devel
    - libjpeg-turbo-devel
setup      : |
    %reconfigure --with-udev-confdir=/usr/lib64/udev
build      : |
    %make
install    : |
    %make_install
