name       : utsushi
version    : 3.65.0
release    : 18
source     :
    - http://support.epson.net/linux/src/scanner/imagescanv3/debian/imagescan_3.65.0.orig.tar.gz : e83704398c51a3166fd62c25b89e95cf6262e52f3dc6e627db3e7556e2220d64
license    : GPL-3.0-or-later
component  : office
summary    : Utsushi - Next Generation Image Acquisition
description: |
    Utsushi for Epson scanning, replaces iscan/imagescan
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(GraphicsMagick++)
    - pkgconfig(ImageMagick)
    - pkgconfig(libtiff-4)
    - pkgconfig(libudev)
    - pkgconfig(libusb-1.0)
    - pkgconfig(sane-backends)
    - libboost-devel
    - libjpeg-turbo-devel
setup      : |
    %patch -p1 < $pkgfiles/boost-1.74.patch
    %configure --with-udev-confdir=/usr/lib64/udev \
               --enable-sane-config \
               --enable-udev-config
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/utsushi.desktop $installdir/usr/share/applications/utsushi.desktop
